name: vHive integration tests

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
  workflow_dispatch:

env:
  GOOS: linux
  GO111MODULE: on

jobs:
  integration-tests:
    name: Integration tests
    runs-on: [self-hosted , integ]
    strategy:
      fail-fast: false
      matrix:
        test-name: [test, test-man-bench]
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -race -v -a ./...

    - name: Run vHive end-to-end tests
      run: make ${{ matrix.test-name }}

    - name: Cleaning
      if: ${{ always() }}
      run: ./scripts/clean_fcctr.sh
