name: vHive nightly integration tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  GOOS: linux
  GO111MODULE: on

jobs:
  integration-tests:
    name: Test all functions
    runs-on: [self-hosted, nightly, integ]
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -race -v -a ./...

    - name: Run all function tests
      run: make nightly-test

    - name: Cleaning
      if: ${{ always() }}
      run: ./scripts/clean_fcctr.sh
